import { makeStyles } from "@material-ui/core";
import logoimg1 from './images/icon-work.svg';
import logoimg2 from './images/icon-play.svg';
import logoimg3 from './images/icon-study.svg';
import logoimg4 from './images/icon-exercise.svg';
import logoimg5 from './images/icon-social.svg';
import logoimg6 from './images/icon-self-care.svg';

export const useStyles = makeStyles((theme) => ({


  outerCarda: {
    position: 'relative',
    background: `url(${logoimg1}) no-repeat right top / cover`,
    backgroundSize: '40% 30%',
    backgroundColor: 'red',
    maxWidth: '100%',
    margin: '0 auto',
    width:"200px",
    height: "230px",
    marginLeft:"10px",
    marginBottom: theme.spacing(2),
    backgroundColor: "#F3966F",
    borderRadius: "10px",
   
    '&:before': {
      content: '""',
      display: 'block',
      position: 'absolute',
      top: 0,
      left: 0,
      width: '100%',
      height: '100%',
      backgroundColor: '#F3966F',
      opacity: 0.5,
      zIndex: 1,
    },
  },
  outerCardb: {
    position: 'relative',
    background: `url(${logoimg2}) no-repeat right top / cover`,
    backgroundSize: '40% 30%',
    backgroundColor: 'red',
    maxWidth: '100%',
    margin: '0 auto',
    width:"200px",
    height: "230px",
    marginLeft:"10px",
    marginBottom: theme.spacing(2),
    backgroundColor: "#9FEFFC",
    borderRadius: "10px",
    '&:before': {
      content: '""',
      display: 'block',
      position: 'absolute',
      top: 0,
      left: 0,
      width: '100%',
      height: '100%',
      backgroundColor: '#9FEFFC',
      opacity: 0.5,
      zIndex: 1,
    },
  },
  outerCardc: {
    position: 'relative',
    background: `url(${logoimg3}) no-repeat right top / cover`,
    backgroundSize: '40% 30%',
    backgroundColor: 'red',
    maxWidth: '100%',
    margin: '0 auto',
    width:"200px",
    height: "230px",
    marginLeft:"10px",
    marginBottom: theme.spacing(2),
    backgroundColor: "#F78371",
    borderRadius: "10px",
    '&:before': {
      content: '""',
      display: 'block',
      position: 'absolute',
      top: 0,
      left: 0,
      width: '100%',
      height: '100%',
      backgroundColor: '#F78371',
      opacity: 0.5,
      zIndex: 1,
    },
  },
  outerCardd: {
    position: 'relative',
    background: `url(${logoimg4}) no-repeat right top / cover`,
    backgroundSize: '40% 30%',
    backgroundColor: 'red',
    maxWidth: '100%',
    margin: '0 auto',
    width:"200px",
    height: "230px",
    marginLeft:"10px",
    marginBottom: theme.spacing(2),
    backgroundColor: "#7DF9B1",
    borderRadius: "10px",
    '&:before': {
      content: '""',
      display: 'block',
      position: 'absolute',
      top: 0,
      left: 0,
      width: '100%',
      height: '100%',
      backgroundColor: '#7DF9B1',
      opacity: 0.5,
      zIndex: 1,
    },
  },
  outerCarde: {
    position: 'relative',
    background: `url(${logoimg5}) no-repeat right top / cover`,
    backgroundSize: '40% 30%',
    backgroundColor: 'red',
    maxWidth: '100%',
    margin: '0 auto',
    width:"200px",
    height: "230px",
    marginLeft:"10px",
    marginBottom: theme.spacing(2),
    backgroundColor: "#D97DF9",
    borderRadius: "10px",
    '&:before': {
      content: '""',
      display: 'block',
      position: 'absolute',
      top: 0,
      left: 0,
      width: '100%',
      height: '100%',
      backgroundColor: '#D97DF9',
      opacity: 0.5,
      zIndex: 1,
    },
  },
  outerCardf: {
    position: 'relative',
    background: `url(${logoimg6}) no-repeat right top / cover`,
    backgroundSize: '40% 30%',
    backgroundColor: 'red',
    maxWidth: '100%',
    margin: '0 auto',
    width:"200px",
    height: "230px",
    marginLeft:"10px",
    marginBottom: theme.spacing(2),
    backgroundColor: "#F9E87D",
    borderRadius: "10px",
    '&:before': {
      content: '""',
      display: 'block',
      position: 'absolute',
      top: 0,
      left: 0,
      width: '100%',
      height: '100%',
      backgroundColor: '#F9E87D',
      opacity: 0.5,
      zIndex: 1,
    },
  },
  
  innerCard: {
    width:"200px",
    height: "220px",
    marginTop: "25px",
    marginLeft: "-16px",
    borderRadius:"16px",
    borderColor: "black",
    backgroundColor: "#151B54",
    color:"white",
    boxShadow: "0px 2px 5px 1px rgba(0,0,0,0.25)",
    position: 'relative',
    zIndex: 2,
  },
  image2: {
    width: '20%',
    marginLeft: '50px',
    height: 'auto',
  },
  outerCard2: {
    width:"250px",
    height: "400px",
  
marginLeft:"150px",
   marginBottom:"40px",
    backgroundColor: "#f1f1f1",
    borderRadius: "10px",
  },
  innerCard2: {
    width:"250px",
    height: "300px",
    marginTop:"-60px",
    marginLeft: "-16px",
    borderRadius:"16px",
    backgroundColor: "#ffffff",
    boxShadow: "0px 2px 5px 1px rgba(0,0,0,0.25)",
  },
  outer: {
    marginTop:"300px",
    fontSize: "12px",
   },
   outer2: {
    marginTop:"-300px",
    fontSize: "12px",
   },
  type2: {
   fontSize: "12px",
  },
  box2: {
    backgroundColor: "white",
    fontSize: "12px",
    width: "200px",
    height: "400px",
   },
   box3: {
    fontSize: "15px",
    width: "100px",
    height: "100px",
    marginTop: "-20px",
    backgroundColor: "red",
   },

  type3: {
    fontSize: "45px",
    marginTop: '20px',
   },
  grid1: {
    marginLeft: "40px",
  },

  grid2: {
    marginLeft: "-200px",
  },
  imgelogo: {
    marginTop: "-20px",
    marginLeft: "100px",
  }
}));


